# Generated by Django 4.0.2 on 2022-03-05 06:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Manufacturer',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('manufacturer', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('address', models.CharField(max_length=200)),
                ('phone_number', models.CharField(max_length=15)),
                ('country', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('category', models.CharField(max_length=20)),
                ('car_model', models.CharField(max_length=20)),
                ('year', models.IntegerField(default=0)),
                ('series', models.CharField(max_length=20)),
                ('manufacturer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ex2_app.manufacturer')),
            ],
        ),
    ]
